<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Optimize>true</Optimize>
    <ImageSharpReference Condition="'$(ImageSharpReference)' == ''">$(NuGetPackageRoot)sixlabors.imagesharp\3.1.12\lib\net6.0\SixLabors.ImageSharp.dll</ImageSharpReference>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Tiesky.Image2D\Tiesky.Image2D.csproj" />
    <Reference Include="SixLabors.ImageSharp" HintPath="$(ImageSharpReference)" Private="true" />
  </ItemGroup>
</Project>
